//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationFPTGroup14.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseForRent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HouseForRent()
        {
            this.Images = new HashSet<Image>();
            this.Posts = new HashSet<Post>();
            this.Renters = new HashSet<Renter>();
        }
    
        public int HouseID { get; set; }
        public Nullable<int> Acreage { get; set; }
        public Nullable<long> Price { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> TownshipID { get; set; }
        public Nullable<bool> InnerBathRoom { get; set; }
        public Nullable<bool> Parking { get; set; }
        public Nullable<int> MaxPeople { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string Note { get; set; }
        public string AccountID { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsHouse { get; set; }
        public Nullable<bool> Kitchenshelf { get; set; }
        public Nullable<bool> Mezzanine { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual City City { get; set; }
        public virtual Status Status { get; set; }
        public virtual Township Township { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Posts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Renter> Renters { get; set; }
    }
}
