//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationFPTGroup14.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Renter
    {
        public int ID { get; set; }
        public string RenterID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string Phone { get; set; }
        public string Note { get; set; }
        public Nullable<int> HouseID { get; set; }
        public Nullable<System.DateTime> RentDate { get; set; }
    
        public virtual HouseForRent HouseForRent { get; set; }
    }
}
