//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationFPTGroup14.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchResult
    {
        public int PostID { get; set; }
        public string PostTitle { get; set; }
        public Nullable<int> PostView { get; set; }
        public Nullable<System.DateTime> PostDay { get; set; }
        public string Description { get; set; }
        public Nullable<int> Acreage { get; set; }
        public Nullable<long> Price { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> TownshipID { get; set; }
        public Nullable<bool> InnerBathRoom { get; set; }
        public Nullable<bool> Parking { get; set; }
        public Nullable<int> MaxPeople { get; set; }
        public string Note { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsHouse { get; set; }
        public string Name { get; set; }
        public string CityName { get; set; }
        public Nullable<bool> Kitchenshelf { get; set; }
        public Nullable<bool> Mezzanine { get; set; }
        public int HouseID { get; set; }
        public string Mail { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<bool> Status { get; set; }
        public int StatusID { get; set; }
        public string AccountID { get; set; }
    }
}
